### ISSUE TITLE
WAN-only/LAN-only modes?

### ISSUE THREAD

**Issue by LynHyper** [hyprspace/hyprspace#28]
It'd be nice to have the ability to have hyprspace isolated to just the WAN or just the LAN network depending on what it will be used for.

To my understanding, hyprspace's node publishes the multiaddresses for both the private and public ip-addresses, this either exposes the inner network topology in the LAN case or publishes the public ip-address for a hyprspace node intended for local use only in the WAN case. Being able to disabled either would solve the above issues.

Would do you think?

**Comment by alecbcs** [comment]
This could be interesting! The only issue might be portability if say you limit a node to LAN only and then forget and try to connect to it from out of the local network. It would be helpful to get more information on how people are using Hyprspace to see how many people this would help if you wanted to disable one network or another, versus people who jump between local and remote networks frequently and want both available.

**Comment by LynHyper** [comment]
That is a good point, maybe `hyprspace init` should print if it's in LAN/WAN only mode just to make sure people don't accidently set it to one and forget?

**Comment by LynHyper** [comment]
Just thought of a better way of handling this.

Restricting hyprspace to just WAN or LAN would affect portability. So instead, what about an allow and deny list within the hyprspace config to allow or reject traffic coming from outside of hyprspace, for example:

```
interface:
  name: hs0
  id: QmFoo
  listen_port: 8001
  address: 10.1.1.1/24
  allow_address: 192.168.0.0/24  [Only accepts connections, hyprspace node or not, with 192.168.0.0/24 source addresses]
  deny_address: 10.2.1.0/24  [Denies connections, hyprspace node or not, with 10.2.1.0/24 source addresses]
  private_key: !!binary |
PRIVATE_KEY

peers:
  10.1.1.1:
    id: QmFoa
```

This allows fine grain control, even allowing you to narrow down to a specific VPN by it's ip-range, thus making it more versatile than a simple WAN or LAN mode.
