### ISSUE TITLE
Can't ping between devices

### ISSUE THREAD

**Issue by LynHyper** [hyprspace/hyprspace#40]
Trying to setup a hyprspace connection between my PC and laptop, on the PC's side I'm getting:
```
[+] Creating TUN Device
[+] Creating LibP2P Node
[+] Setting Up Node Discovery via DHT
[+] Network Setup Complete...Waiting on Node Discovery
[+] Connection to 10.1.1.2 Successful. Network Ready.
[+] Successfully Created Hyprspace Daemon
```
```
ip a

12: hs0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1420 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none
    inet 10.1.1.1/24 scope global hs0
       valid_lft forever preferred_lft forever
    inet6 fe80::2041:4e1d:da41:ba84/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
```
And on the laptop's side I'm getting:
```
[+] Creating TUN Device
[+] Creating LibP2P Node
[+] Setting Up Node Discovery via DHT
[+] Network Setup Complete...Waiting on Node Discovery
[+] Successfully Created Hyprspace Daemon
```
```
ip a

12: hs1: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1420 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none
    inet 10.1.1.1/24 scope global hs0
       valid_lft forever preferred_lft forever
    inet6 fe80::2041:4e1d:da41:ba84/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
```
I've only gotten the `Connection to` output to happen once on the PC, all other attempts from then didn't show it, I'm using the latest release on github.

**Comment by alecbcs** [comment]
@LynHyper can you share your configs from both clients? (Please redact the public & private keys, as well as the discovery key.)

**Comment by LynHyper** [comment]
I've managed to get the right `Connection to ...` outputs on both sides, copy and pasted the PeerIDs on both sides and that seems to have solved the initial problem, but, I still can't ping from either device.

**Comment by LynHyper** [comment]
PC:
```
interface:
  name: hs0
  id: QmFoo
  listen_port: 8001
  address: 10.1.1.1/24
  discover_key: discovery-key-here
  private_key: !!binary |
    Private key here
peers:
  10.1.1.2:
    id: QmFoa
```
Laptop:
```
interface:
  name: hs1
  id: QmFoa
  listen_port: 8001
  address: 10.1.1.1/24
  discover_key: discovery-key-here
  private_key: !!binary |
    Private key here
peers:
  10.1.1.3:
    id: QmFoo
```
